#!/usr/bin/env python
# GstSinksTester - Interactive tests for GStreamer audio and video sinks
# Copyright (C) 2012 Andoni Morales Alastruey <ylatuya@gmail.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

import argparse
import gettext
import os
import sys
from datetime import datetime

import pygst
pygst.require('0.10')
import pygtk
pygtk.require('2.0')

import gtk

from gst_sink_test import Test

_ = gettext.gettext
N_ = lambda x: x


description = N_('Runs interative tests for GStreamer audio and video sinks')


class TestResults(object):

    def __init__(self, filename):
        self.results = {}
        self.filename = filename

    def add_test(self, sink_name, caps, succeed):
        succeed = succeed and 'SUCCESS' or 'ERROR'
        self.results.setdefault(sink_name, []).append((caps, succeed))

    def save(self):
        with open(self.filename, 'w+') as f:
            for sink, tests in self.results.iteritems():
                for test in tests:
                    f.write('%s;%s;%s\n' % (test[1], sink, test[0]))


class Main(object):

    def __init__(self, args):
        self.create_parser()
        self.parse_arguments(args)
        self.test_filename = os.path.join(self.output_dir, self.format_name())
        self.test_started = False
        self.results = None
        self.create_main_window()

    def create_main_window(self):
        self.window = gtk.Window(gtk.WINDOW_TOPLEVEL)
        self.window.connect("delete_event", self.delete_event)
        self.window.connect("destroy", self.destroy)
        self.button = gtk.Button("Start test")
        self.button.connect("clicked", self.start_tests_clicked, None)
        self.window.add(self.button)
        self.window.set_position(gtk.WIN_POS_CENTER)
        self.window.resize(320, 240)
        self.button.show()
        self.window.show()

    def delete_event(self, widget, event, data=None):
        return self.test_started and gtk.TRUE or gtk.FALSE

    def destroy(self, widget, data=None):
        if self.results is not None:
            self.results.save()
        gtk.mainquit()

    def start_tests_clicked(self, widget, data=None):
        self.test_started = True
        self.window.hide()
        self.run_tests()

    def run_tests(self):
        self.results = TestResults(self.test_filename)
        if self.sink is None:
            print "no sinks set"
            gtk.mainquit()
        test = Test(self.sink, self.results)
        test.run()

    def format_name(self):
        return '%s-%s.results' % (self.sink,
                datetime.now().isoformat().replace(':', '_'))

    def create_parser(self):
        ''' Creates the arguments parser '''
        self.parser = argparse.ArgumentParser(description=_(description))
        self.parser.add_argument('sink',
                    help=_('name of the sink to test'))
        self.parser.add_argument('-o', '--output-dir', type=str, default='.',
                    help=_('output directory for the test results'))

    def parse_arguments(self, args):
        ''' Parse the command line arguments '''
        args = self.parser.parse_args(args)
        self.sink = args.sink
        self.output_dir = args.output_dir


if __name__ == "__main__":
    Main(sys.argv[1:])
    gtk.mainloop()
